spring:
  elasticsearch:
    uris: https://organizee-tcc.es.us-central1.gcp.cloud.es.io
    connection-timeout: 1s
    read-timeout: 1m
    password: nK9u2reJpCcQGfdDkjTWrNpO
    username: elastic
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:postgresql://ec2-34-235-198-25.compute-1.amazonaws.com:5432/d52rtcth5np5lb
    username: ipqbfrdlfthtgu
    password: 30be57d12dd7771a27286351ab904b95d508247166129353b1060bab1a64d925
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken%40system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/organizee-b7ef9
aws:
  cloudsearch:
    accessKey: AKIATC7RN2RPSKMXPH2V
    secretKey: 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
    region: us-east-1

search:
  endpoint: search-guide-organizee-domain-rgfor5r6pcnyl2ubppcwphenau.us-east-1.cloudsearch.amazonaws.com
  suggester: title_suggester
