#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:postgresql://ec2-34-235-198-25.compute-1.amazonaws.com:5432/d52rtcth5np5lb
#    username: ipqbfrdlfthtgu
#    password: 30be57d12dd7771a27286351ab904b95d508247166129353b1060bab1a64d925
#    driver-class-name: org.postgresql.Driver

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/test_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver